#!/usr/bin/env python
"""Download the hosted precomputed model-figure cut so a fresh clone can regenerate the figures.

Reads the in-repo manifest (``data/precomputed_manifest.json`` — the OSF ``osf_guid``, the
``osf_zip`` remote filename, an optional ``zip_sha256``, and per-file sha256), fetches the single
zip from that OSF component, extracts it into ``--dest``, and verifies every file against the
manifest. Re-running re-verifies (and only re-fetches if the local cut is missing/mismatched).

    python download_precomputed.py --dest _precomputed_cut
    OSF_TOKEN=... python download_precomputed.py --dest _precomputed_cut     # only if the component is private
    python download_precomputed.py --dest _precomputed_cut --from-local /path/to/mirror   # offline

Then render the figures from the cut:
    python make_all_figures.py --input-source precomputed --derivatives-root _precomputed_cut

Only the INPUT cut (what the figure scripts read) is downloaded; the figures themselves are
regenerated by make_all_figures.py, not fetched.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # make `src` importable standalone
from src.core import precomputed  # noqa: E402

_HERE = Path(__file__).resolve().parent
_MANIFEST = _HERE / "data" / "precomputed_manifest.json"


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dest", default="_precomputed_cut",
                   help="Directory to extract the cut into (default: ./_precomputed_cut). "
                        "Pass this same path to make_all_figures.py --derivatives-root.")
    p.add_argument("--manifest", default=str(_MANIFEST), help="Path to the cut manifest.")
    p.add_argument("--token", default=os.environ.get("OSF_TOKEN"),
                   help="OSF personal access token (default: $OSF_TOKEN). Needed only while the "
                        "component is private; public components download without one.")
    p.add_argument("--no-verify", action="store_true", help="Skip sha256 verification (not recommended).")
    p.add_argument("--from-local", default=None,
                   help="Offline mirror: fetch the zip from <FROM_LOCAL>/<osf_zip> instead of OSF.")
    p.add_argument("--keep-zip", action="store_true",
                   help="Keep the downloaded zip under <dest>/_zip_cache/ instead of deleting it.")
    return p


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    manifest = precomputed.load_manifest(args.manifest)
    dest = Path(args.dest)
    workdir = dest / "_zip_cache"

    guid = manifest.get("osf_guid")
    zip_name = manifest.get("osf_zip")
    print(f"=== {manifest.get('name')} (osf:{guid}) -> {dest} ===")
    if not zip_name:
        print("    ✗ manifest has no 'osf_zip' yet (cut not uploaded).")
        return 1

    if args.from_local:
        fetch = precomputed.local_zip_fetcher(Path(args.from_local))
    else:
        if not guid:
            print("    ✗ manifest has no 'osf_guid' yet — set it after uploading to OSF, "
                  "or use --from-local <mirror>.")
            return 1
        fetch = precomputed.osf_zip_fetcher(guid, token=args.token)

    try:
        precomputed.download_cut_zip(manifest, dest, fetch, workdir=workdir,
                                     verify=not args.no_verify, keep_zip=args.keep_zip)
    except Exception as e:  # noqa: BLE001
        print(f"    ✗ failed: {e}")
        return 1

    try:
        if workdir.is_dir() and not any(workdir.iterdir()):
            workdir.rmdir()
    except OSError:
        pass

    print("\nCut downloaded + verified. Reproduce with:\n"
          f"    python make_all_figures.py --input-source precomputed --derivatives-root {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
