"""Marvi 2025 (EMFL) — dataset config.

Efficient multifunction localizer (Marvi et al., 2025). Precomputed cut = **fMRIPrep
derivatives**: BOLD in 3 spaces (MNI 2mm / native T1w / fsnative) + FreeSurfer
recon-all + CVS `.m3z` warps (docs/DESIGN.md §1). Resolves via `--derivatives-root`.

Analysis constants (subjects, contrasts, GLM params, parcel maps) live in the vendored
`emfl.config` (single source of truth, faithful copy of the dev pipeline). This module
re-exports the release-facing subset and adds the release metadata (raw source /
precomputed cut / hosting). Import `emfl.config` directly for the full set.

Port source: 20251030_Marvi_2025_efficient_fMRI_localizer/src/emfl/config.py (ef1da34).
STATUS: filled during the port (2026-07-06). See README §8.
"""
from __future__ import annotations

from emfl.config import (  # noqa: F401  (re-exported for release-facing callers)
    ALL_SUBJECTS,
    ALL_CONTRASTS,
    VISUAL_CONTRASTS,
    AUDITORY_CONTRASTS,
    RUN_SPLITS,
    PARCEL_CATEGORIES,
    PARCEL_CONTRAST_MAP,
    DEFAULT_SPACE,
    DEFAULT_FROI_PERCENTILE,
    MIN_FROI_VOXELS,
)

DATASET = "Marvi_2025"

# --- Raw source (external, not hosted) — docs/DESIGN.md §5 ---
RAW_SOURCE = {
    "name": "OpenNeuro ds006179",
    "url": "https://openneuro.org/datasets/ds006179",
    "n_subjects": 6,
    "license": "CC0",
}

# --- Precomputed cut (what we ship on OSF) — docs/DESIGN.md §5.1 ---
# fMRIPrep derivatives across the 3 needed spaces + FreeSurfer + CVS warps.
# ⚠ Ship surface-space + defaced anat only (no full-res warpable T1w) — docs/DESIGN.md §5(b).
PRECOMPUTED = {
    "kind": "fmriprep_derivatives",
    "spaces": ["MNI152NLin2009cAsym", "T1w", "fsnative"],
    "extras": ["freesurfer", "cvs_m3z_warps"],
    "osf_guid": "tb9cr",       # OSF component (umbrella ehrt6); https://osf.io/tb9cr/
    "manifest": "data/precomputed_manifest.json",  # in-repo; path+sha256 per file (download_precomputed.py)
    "minimal_subset": None,    # TODO: 1-2 subjects across the needed spaces (sanity tier)
}

# --- Reference-figure renders (metadata only; not consumed by the pipeline) ---
# Reference renders are NOT shipped in this code-only release: Fig. A2 is regenerated by
# make_figures.py, and the heavy native-surface HTML (~10 MB each, base64 mesh) is hosted
# on OSF so a reviewer can grab it without pulling the multi-GB derivatives tier. The paths
# below only record where those artifacts live; nothing in the pipeline reads this dict.
REFERENCE_FIGURES = {
    "in_git": ["docs/reference_figures/replication_of_fig_4_from_Marvi_2025_with_indiv.svg",
               "docs/reference_figures/replication_of_fig_4_from_Marvi_2025_with_indiv.png"],
    "on_osf": {
        "kind": "native_surface_html",
        "staging_dir": "docs/reference_figures/surface_maps",  # gitignored; upload source
        "osf_guid": None,      # TODO(hosting): standalone component, NOT inside PRECOMPUTED
        "manifest": None,      # TODO(hosting): {relpath: {osf_id, sha256}}
        "approx_size": "~990 MB (108 HTML: all 6 subjects x 9 contrasts x L/R, Figs 2&3 native "
                       "surface, dir/file names carry the functional label e.g. __FFA-face/__ToM) "
                       "+ group_contrast_bars (combined grid + 14 per-fROI 2-bar group plots).",
    },
}

# --- Analysis parameters (from emfl.config; re-exported for release-facing callers) ---
SUBJECTS: list[str] = list(ALL_SUBJECTS)   # 6 public EMFL subjects (sub-kaneff01/06/07/08/09/21)
CONTRASTS: list[str] = list(ALL_CONTRASTS) # 9 contrasts (5 visual + 4 auditory)

# Per-condition regressor names, in the fixed Fig. A2 display order (README §6b).
# These are the block regressors the GLM estimates; the 9 CONTRASTS are built from them.
CONDITIONS: list[str] = [
    "faces", "bodies", "scenes", "objects", "words_scr_objects",  # visual
    "false_belief", "false_photo", "nonwords", "quilted_speech", "math",  # auditory
]

SPACE_BRANCH_A = DEFAULT_SPACE   # "MNI152NLin2009cAsym" — Branch A fROI profiles (2mm)
SURFACE_TARGET = "fsnative"      # Branch B surface maps use individual-subject fsnative
FROI_PERCENTILE = DEFAULT_FROI_PERCENTILE  # top 10% t-voxels within each parcel

# Canonical condition-response CSV (Fig. A2 golden master) — pinned (README §1, §6b).
CANONICAL_CONDITION_RESPONSES = "condition_responses_details_20260310_203831.csv"
